spring.application.name=healthcare
server.servlet.context-path=/api/v1
server.port=9999

# Conection data
spring.datasource.url=jdbc:postgresql://localhost:5437/healthcare_db
spring.datasource.username=dev
spring.datasource.password=dev123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


security.jwt.secret-key=Zt9XkQ7P3eR8A2mYF6bD4VnL5SxWcH0JkUo1iE9RMaY