package com.healthcare.modules.audit.enums;

public enum AuditAction {
    // Autenticación y usuarios
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,

    // Gestión de usuarios
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_ROLE_CHANGED,

    // Gestión de pacientes
    PATIENT_CREATED,
    PATIENT_UPDATED,
    PATIENT_DELETED,
    PATIENT_VIEWED,
    PATIENT_MEDICAL_RECORD_UPDATED,

    // Gestión de doctores
    DOCTOR_CREATED,
    DOCTOR_UPDATED,
    DOCTOR_DELETED,
    DOCTOR_VIEWED,
    DOCTOR_SPECIALTY_CHANGED,

    // Gestión de citas
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_ATTENDED,
    APPOINTMENT_NO_SHOW,
    APPOINTMENT_VIEWED,

    // Gestión de consultas
    CONSULTATION_CREATED,
    CONSULTATION_UPDATED,
    CONSULTATION_VIEWED,
    CONSULTATION_PRESCRIPTION_ADDED,

    // Gestión de recordatorios
    REMINDER_CREATED,
    REMINDER_UPDATED,
    REMINDER_DELETED,
    REMINDER_MARKED_READ,
    REMINDER_SENT,
    REMINDER_FAILED,

    // Reportes y exportaciones
    REPORT_GENERATED,
    REPORT_EXPORTED,
    DATA_EXPORTED,
    DATA_IMPORTED,

    // Configuración del sistema
    SYSTEM_SETTINGS_UPDATED,
    SYSTEM_CONFIGURATION_CHANGED,
    SYSTEM_BACKUP_CREATED,
    SYSTEM_RESTORE_PERFORMED,

    // Acciones administrativas
    AUDIT_LOG_VIEWED,
    AUDIT_LOG_EXPORTED,
    PERMISSIONS_CHANGED,

    // Errores y eventos del sistema
    SYSTEM_ERROR,
    SYSTEM_WARNING,
    DATABASE_ERROR,
    INTEGRATION_ERROR,
    EMAIL_SENT,
    EMAIL_FAILED,
    SMS_SENT,
    SMS_FAILED,

    // Operaciones masivas
    BULK_OPERATION_STARTED,
    BULK_OPERATION_COMPLETED,
    BULK_OPERATION_FAILED,

    // Seguridad
    SECURITY_VIOLATION_DETECTED,
    SUSPICIOUS_ACTIVITY,
    ACCESS_DENIED,
    SESSION_EXPIRED,
    SESSION_TERMINATED
}
